## 크몽 데이터팀에 오신 것을 환영합니다!

<img src = 'https://t1.daumcdn.net/thumb/R1280x0/?fname=http://t1.daumcdn.net/brunch/service/user/11Yx/image/jNo1MfbPhIsud4DhAFh5fej9nQA.jpg' width=180 />
    
<center><small><a href="https://kmong.com/">kmong.com</a></small></center>

(이 쥬피터 노트북은 다음의 링크 https://bit.ly/dsa-0102-kmong-ipynb 데이터는 https://bit.ly/dsa-kmong 에서 다운받을 수 있습니다.)
    
안녕하세요! [크몽](https://kmong.com) 데이터팀에 오신 것을 환영합니다.

크몽은 "비합리적인 서비스 시장을 정보기술로 혁신하여 새로운 일자리를 만들고 사람들이 행복하게 일하는 세상을 만든다."는 미션을 가지고 있는 프리랜서 마켓 플랫폼입니다. 크몽팀은 디자인, 마케팅, IT&개발, 컨텐츠 제작, 통번역 등 다양한 서비스 카테고리를 기반으로 직업과 직장의 경계를 허물며 사람들이 스스로 경제 주체가 되어 행복하게 일하는 세상을 만들고 있습니다.

크몽에서는 주어진 데이터를 활용하여 1) 사용자에게 새로운 상품을 추천하거나, 2) 오픈마켓에서 금기시되는 개인간 거래를 발견하 등 다양한 분야에서 데이터와 머신러닝 알고리즘을 사용합니다. 여기에는 크몽의 서비스에서 발생한 다양한 데이터를 사용하게 되는데, 이 부분에서 가장 중요한 것이 바로 데이터를 정리하는 과정, 일명 데이터 클리닝([Data Cleaning](https://en.wikipedia.org/wiki/Data_cleansing))입니다.

실제 데이터분석가로서 현업에 투입되면, 데이터를 분석하는 일보다 데이터를 정리하는 일에 더 많은 시간을 할애하게 됩니다. 통상적으로 전체 업무시간에 70% ~ 80%는 데이터를 정리하는 일을 하게 되는데, 이 과정에서 실력있는 데이터 분석가와 그렇지 않은 데이터 분석가의 차이가 눈에 보이게 됩니다. 실력있는 데이터 분석가는 동일한 분량의 데이터를 2~3시간 안에 처리하는데 비해, 실력이 부족하고 아직 툴에 익숙하지 않은 데이터 분석가는 적어도 반나절, 길면 하루 ~ 이틀 정도의 시간을 투입해야 겨우 동일한 분량의 데이터를 처리하곤 합니다.

그런 의미에서, 오늘 이 쥬피터 노트북을 받은 수강생분은 하루동안 크몽의 일일 데이터 컨설턴트로서 일을 할 것입니다. 여러분들은 오늘 크몽의 사용자 로그 데이터, 웹사이트/모바일 서비스에서 사용자들이 활동한 기록 등을 가져와, 이를 빠른 시간 안에 다듬고 정리하는 일을 맡게 될 것입니다. 하기에 제시한 15개의 데이터 분석 요청을 프로그래밍 언어 파이썬([Python](http://python.org/))과 파이썬의 데이터 분석 패키지 판다스([Pandas](https://www.python.org/))를 활용해 풀어주세요.

숙련된 데이터분석가의 경우 하기의 요청을 늦어도 2시간 내에는 해결할 수 있습니다. 즉, **2시간 안에 모든 문제를 풀 수 있다면 합격입니다.**

문제를 풀 때 다른 자료를 참고하거나, 구글에 검색하는 것 모두 허용합니다. (문제 중에는 구글에 검색하지 않으면 풀 수 없는 문제도 준비해놓았습니다) 관련 자료는 [10 minutes to pandas](https://pandas.pydata.org/pandas-docs/stable/10min.html)를 강력 추천합니다. 또한 이번 과제는 파이썬에 대한 이해도가 높을수록 문제를 풀기가 수월해집니다. 때문에 [점프 투 파이썬](https://wikidocs.net/book/1)을 사전에 예습하시는 걸 추천드리며, 이중에서도 [문자열 자료형](https://wikidocs.net/13) 부분을 집중해서 읽어보고 실습하는 걸 추천드립니다)

또한 과제를 풀다가 궁금한 점이 있으면 언제든지 우하단의 채팅방에 질문 주시면, 강사 또는 조교가 친절하게 답변 드리도록 하겠습니다. 질문의 분량이 많을 경우 채팅방이 아닌 datascience@dsschool.co.kr 로 문의 주시면 조금 더 상세하게 답변 드릴 수 있습니다.

(하단의 코드는 쥬피터 노트북에서 채팅방을 불러오는 코드입니다. 이 코드는 수정하지 않고 가만히 놔두시면 됩니다.)

In [2]:
# 파이썬의 import를 활용해 데이터 분석용 패키지인 판다스(Pandas)를 읽어옵니다.
import pandas as pd

# 판다스 데이터프레임(DataFrame)을 출력할 때, 최대 출력할 수 있는 컬럼을 100개로 늘려줍니다.
# 이렇게 해야 데이터를 분석할 때 출력해서 확인하기 편합니다.
pd.options.display.max_columns = 100

### 데이터 로딩하기

먼저 데이터를 로딩해오겠습니다. 데이터를 읽어올때는 [판다스(Pandas)](https://pandas.pydata.org/)의 [read_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) 라는 기능을 사용합니다.

여기서 파일의 경로를 지정하는 방법에 주의하셔야 합니다. read_csv를 실행할 때 (**FileNotFoundError**)라는 이름의 에러가 난다면 경로가 제대로 지정이 되지 않은 것입니다. 만일 파일의 경로를 지정하는 법이 생각나지 않는다면 [다음의 링크](http://88240.tistory.com/122)를 통해 경로를 지정하는 법을 복습해주세요.

**kmong-conversion.csv**

먼저 크몽의 로그 데이터를 하나씩 가져오겠습니다. 가장 처음 가져올 데이터는 크몽의 가장 핵심 데이터라고 할 수 있는 ```kmong-conversion.csv``` 입니다. 여기에는 사용자가 크몽의 웹사이트/모바일 서비스에서 활동한 모든 활동 기록(activity)이 상세하게 담겨져 있으며, 이 정보를 바탕으로 데이터를 분석하여 사용자의 패턴을 유추할 수 있습니다. 컬럼 정보는 다음과 같습니다.

* ```eventcategory```: 앱의 이벤트에 대한 카테고리입니다. 크게 다음의 종류가 있습니다.
  - ```install```: 앱설치
  - ```launch```: 앱실행 
  - ```deeplinkLaunch```: 딥링크 통한 앱실행
  - ```goal```: 앱 내에서의 활동 여부
  - ```exit```: 앱 종료
  - ```foreground```, background```: 앱을 foreground, background로 전환
  - ```launchlnSession```: Session의 시작.
* ```isfirstactivity```: 해당 이벤트가 해당 유저에 한하여 첫 번째인지 혹은 두 번째 이상인지를 알려주는 값입니다. 
  - boolean 형식으로, 해당 이벤트가 해당 유저에 한하여 첫 번째 이벤트이면 True, 아니면 False를 갖습니다.
* ```apppackagename```: 앱의 패키지의 고유한 이름입니다. 안드로이드의 경우 applicationId을, iOS의 경우 Bundle ID를 가져오게 됩니다.
* ```appversion```: kmong 어플리케이션의 버전입니다.
* ```devicetype```: 사용자가 kmong app을 실행하고 있는 기기의 제품명입니다.
* ```devicemanufacturer```: 사용자가 kmong app을 실행하고 있는 기기의 제조회사입니다. 
* ```osversion```: 사용자가 kmong app을 실행하고 있는 기기의 os 버전입니다.
* ```canonicaldeviceuuid```: 사용자가 kmong app을 실행하고 있는 기기의 고유 식별자입니다. (사용자를 구분하는 식별자로 이용할 수 있습니다)
* ```sourcetype```: 해당 로그를 만든 고객이 유입된 경로입니다. 유료 광고 채널, 바이럴 채널, 앱 마켓 등으로 구분합니다.
* ```channel```: sourcetype과 동일하지만 조금 더 세분화되어 있습니다.
  - unattributed, WEB, google-play, m_naver, google, (not set), google.adwords, m_naverpowercontents, pc_naver, apple.searchads, facebook, m_daum
* ```params_campaign```: 마케터가 입력한 캠페인 파라미터 중 캠페인명입니다. 
* ```params_medium```: 마케터가 입력한 캠페인 파라미터 중 매체입니다.
* ```params_term```: 마케터가 입력한 캠페인 파라미터 중 키워드입니다.
* ```inappeventcategory```: 인앱이벤트 식별자값으로 인앱이벤트를 지칭하는 3개의 값(category > action > label) 중 가장 상위에 속하는 구분값입니다.
  - ```eventcategory```가 goal인 경우에만 제공됩니다.
  - 차후에 읽어올 funnel 데이터셋과 연결할 수 있습니다.
  - ex) seller_selling_history.view, gig_detail.view
* ```inappeventlabel```: categoryid와 동일합니다.
  - 차후에 읽어올 category 데이터셋과 연결할 수 있습니다.
  - 인앱이벤트를 지칭하는 3개의 값(category > action > label) 중 마지막에 속하는 구분값입니다.
* ```eventdatetime```: 모바일 클라이언트 상에서의 실제 이벤트 발생시간입니다. ISO 8601 표준에 따라서 제공됩니다. 
* ```isfirstgoalactivity```: goal 이벤트의 경우, 해당 Goal Label, Description, Key, Category를 가진 이벤트가 해당 유저에 한하여 첫 번째인지 혹은 두 번째 이상 인지를 알려주는 boolean 값입니다. 예를 들어 동일한 유저로부터 두 번 이상의 같은 Goal 이벤트가 발생한 경우(e.g. 동일한 물건 재구매 등) 이 값은 false가 됩니다.

* ```event_rank```: 데이터를 정렬하는데 필요한 컬럼입니다. log엔 기록되지 않으며, DS_School에서 제공하는 전처리된 컬럼입니다.

In [3]:
# 판다스(pandas)의 read_csv를 활용하여 크몽의 전환 정보(conversion) 관련 기록을 저장한 kmong-conversion.csv을 읽어옵니다.
# 이 데이터를 raw_log라는 이름의 변수에 할당합니다.
raw_log = pd.read_csv("data/kmong-conversion.csv")

# raw_log 변수에 할당된 데이터의 행렬 사이즈를 출력합니다.
# 출력은 (row, column) 으로 표시됩니다.
print(raw_log.shape)

# head()로 raw_data 데이터의 상위 5개를 띄웁니다.
#raw_log.head()

(434244, 19)

In [4]:
raw_log.columns

Index(['eventcategory', 'isfirstactivity', 'apppackagename', 'appversion',
       'devicetype', 'devicemanufacturer', 'osversion', 'canonicaldeviceuuid',
       'sourcetype', 'channel', 'params_campaign', 'params_medium',
       'params_term', 'inappeventcategory', 'inappeventlabel', 'eventdatetime',
       'rowuuid', 'isfirstgoalactivity', 'event_rank'],
      dtype='object')

**kmong-funnel.csv**

그 다음 가져올 데이터셋은 퍼널(Funnel) 정보를 나타내는 ```kmong-funnel.csv``` 입니다. 퍼널은 사용자가 서비스에 접속한 뒤 상품을 구매하기까지의 모든 경로를 구조화 한 것을 의미합니다. 

사용자가 특정 상품을 결제하기 위해선, 해당 상품의 설명을 적은 페이지를 방문해야 하며, 상품 설명 페이지를 방문하기 위해서는 해당 상품이 리스트되어있는 페이지를 방문해야 합니다. 이런 방식으로 웹사이트를 설명하는 것을 일명 퍼널이라고 합니다.

<img src="https://cdn-images-1.medium.com/max/1600/0*voRGTKciwKuIb2HS.png" width=480 />

<br />
<center><small>사용자가 처음 유입(Acquistion) 되었을 때부터 구매(Revenue)를 할 때 까지의 모든 과정을 깔때기로 묘사한 것을 퍼널이라고 합니다.
<br />    
(참고 자료: <a href="https://medium.com/the-school-of-mobile/app-marketing-metrics-for-pirates-growth-hacking-the-purchase-funnel-b4f1219c5945">App Marketing Metrics for Pirates: Growth Hacking the Purchase Funnel</a>)</small></center>

이 퍼널 정보를 이용해 사용자가 상품을 구매하는 전환(Conversion) 여부, 내지는 서비스를 이탈하는 이탈(Churn) 여부를 추적할 수 있으며, 이를 통해서 웹사이트나 모바일서비스를 개선하여 전환율을 높이고 이탈률을 낮출 수 있습니다. 크몽에서는 서비스에서 사용하는 퍼널에 대한 설명을 ```kmong-funnel.csv``` 파일에 저장해두고 있습니다.

In [5]:
# 판다스(pandas)의 read_csv를 활용하여 크몽의 퍼널(funnel) 관련 기록을 저장한 kmong-funnel.csv을 읽어옵니다.
# 이 데이터를 raw_funnel라는 이름의 변수에 할당합니다.
raw_funnel = pd.read_csv("data/kmong-funnel.csv")

# raw_funnel 변수에 할당된 데이터의 행렬 사이즈를 출력합니다.
# 출력은 (row, column) 으로 표시됩니다.
print(raw_funnel.shape)

# funnel 데이터 전체를 출력합니다.
#raw_funnel

(53, 6)

**kmong-category.csv**

마지막으로 가져올 데이터셋은 크몽에서 판매하는 상품의 카테고리를 나타내는 ```kmong-category.csv``` 입니다. 크몽에서는 디자인, 번역, 컨텐츠 제작등 다양한 상품을 판매하고 있는데, 이 상품을 그룹화하고 정리할 수 있도록 만든 것이 카테고리입니다. 크몽에서는 이 값을 ```kmong-category.csv``` 라는 변수에 저장해두고 있습니다.

In [6]:
# 판다스(pandas)의 read_csv를 활용하여 크몽의 카테고리(category) 관련 기록을 저장한 kmong-category.csv을 읽어옵니다.
# 이 데이터를 raw_category라는 이름의 변수에 할당합니다.
raw_category = pd.read_csv("data/kmong-category.csv")

# raw_category 변수에 할당된 데이터의 행렬 사이즈를 출력합니다.
# 출력은 (row, column) 으로 표시됩니다.
print(raw_category.shape)

# funnel 데이터 전체를 출력합니다.
#raw_category

(245, 9)

### 데이터 정리하기

먼저 가장 기본이 되는 ```kmong-conversion.csv```부터 정리하겠습니다. 이 데이터에는 사용자의 활동 기록을 자세하게 정리하였다는 장점이 있지만, 데이터가 다소 지저분하게 기록되어 있기 때문에, 이 데이터를 정리하지 않은 채 분석하는 것은 많은 시간을 낭비하게 될 것 같습니다. 그러므로 이번 기회에 데이터를 깔끔하게 정리하여 저장하도록 하겠습니다.

**1. ```canonicaldeviceuuid``` 컬럼명을 ```userid``` 컬럼명으로 바꿔주세요.**

먼저 ```canonicaldeviceuuid```라는 컬럼명을 바꾸고 싶습니다. 이 컬럼은 크몽을 이용하는 한 명의 사용자를 나타내는 중요한 정보임에는 틀림없지만, ```canonicaldeviceuuid```라는 표현 자체가 크몽, 내지는 다른 몇몇 분야에서만 쓰이는 표현이기 때문에 이 데이터를 처음 보는 사람의 입장에서는 직관적으로 이해하기 힘듭니다. 그렇기 때문에 이 컬럼의 이름을 많은 사람들이 직관적으로 이해할 수 있는 ```userid```로 바꾸고 싶습니다. 최종적으로 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe", style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>canonicaldeviceuuid</th>
            <th>userid</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957</td>
            <td>F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957</td>
        </tr>
        <tr>
            <th>1</th>
            <td>8a871e50-0717-4aed-9bad-04ac3c3793be</td>
            <td>8a871e50-0717-4aed-9bad-04ac3c3793be</td>
        </tr>
        <tr>
            <th>2</th>
            <td>A9E5778A-8F3D-4597-9718-74BF953A9F64</td>
            <td>A9E5778A-8F3D-4597-9718-74BF953A9F64</td>
        </tr>
        <tr>
            <th>3</th>
            <td>168761CB-CB67-4592-867D-52780D651297</td>
            <td>168761CB-CB67-4592-867D-52780D651297</td>
        </tr>
        <tr>
            <th>4</th>
            <td>ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D</td>
            <td>ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D</td>
        </tr>
    </tbody>
</table>

In [7]:
# Write your code here!

#raw_log.columns: copy all columns and just change canonicaldeviceuuid to userid 
raw_log.columns = ['eventcategory', 'isfirstactivity', 'apppackagename', 'appversion',
       'devicetype', 'devicemanufacturer', 'osversion', 'userid',
       'sourcetype', 'channel', 'params_campaign', 'params_medium',
       'params_term', 'inappeventcategory', 'inappeventlabel', 'eventdatetime',
       'rowuuid', 'isfirstgoalactivity', 'event_rank']
#raw_log.columns

**2. ```eventdatetime``` 컬럼은 datetime 형태로 바꾼 뒤 연/월/일/시/분/초 데이터를 추출해주세요.**

```eventdatetime```은 날짜와 시간 형식으로 표현되어 있습니다. (ex: 2018-01-01T00:00:00+09:00) 하지만 이 데이터를 처음 읽을 때, 판다스는 날짜 데이터로 인식하지 않고 문자열(object, 내지는 string)으로 인식합니다. 이 데이터를 날짜와 시간 형식을 나타내는 ```datetime``` 형태로 바꾼 뒤, 연/월/일/시/분/초 데이터를 추출해주세요. 최종적으로 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>eventdatetime</th>
            <th>eventdatetime_year</th>
            <th>eventdatetime_month</th>
            <th>eventdatetime_day</th>
            <th>eventdatetime_hour</th>
            <th>eventdatetime_minute</th>
            <th>eventdatetime_second</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
        </tr>
        <tr>
            <th>1</th>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
        </tr>
        <tr>
            <th>2</th>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
        </tr>
        <tr>
            <th>3</th>
            <td>2018-09-27 15:00:01</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>1</td>
        </tr>
        <tr>
            <th>4</th>
            <td>2018-09-27 15:00:02</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>2</td>
        </tr>
    </tbody>
</table>

In [8]:
# Write your code here!
from datetime import datetime
#raw_log.info()

In [9]:
# split date_time and micro time
# micro time not being used
records = []
for name in raw_log['eventdatetime']:
    records.append(name.split("+")[0])

In [10]:
date_time=pd.to_datetime(records, format = "%Y-%m-%dT%H:%M:%S")

In [11]:
df_datetime = pd.DataFrame(date_time, columns = ['eventdatetime'])

In [12]:
df_datetime['eventdatetime_year'] = date_time.year
df_datetime['eventdatetime_year'] = date_time.year
df_datetime['eventdatetime_month'] = date_time.month
df_datetime['eventdatetime_day'] = date_time.day
df_datetime['eventdatetime_hour'] = date_time.hour
df_datetime['eventdatetime_minute'] = date_time.minute
df_datetime['eventdatetime_second'] = date_time.second

In [13]:
df_datetime.head()

,eventdatetime,eventdatetime_year,eventdatetime_month,eventdatetime_day,eventdatetime_hour,eventdatetime_minute,eventdatetime_second
0,2018-09-28 00:00:00,2018,9,28,0,0,0
1,2018-09-28 00:00:00,2018,9,28,0,0,0
2,2018-09-28 00:00:00,2018,9,28,0,0,0
3,2018-09-28 00:00:01,2018,9,28,0,0,1
4,2018-09-28 00:00:02,2018,9,28,0,0,2

**3. ```osversion``` 컬럼에 들어가 있는 정보를 여러 개의 컬럼으로 나눠주세요.**

```osversion``` 컬럼을 사용자가 현재 사용하고 있는 스마트폰 디바이스의 운영체제와 그 버전을 나타냅니다. 여기에는 크게 1) 현재 사용하고 있는 운영체제(Operating System, 이하 OS), 2) 그리고 해당 운영체제의 버전(version) 정보가 기록되어 있습니다. 가령 ```osversion```에 들어있는 값이 iOS11.4.1이라면, 이 스마트폰의 운영체제는 iOS(아이폰), 운영체제의 버전은 11.4.1 이라는 사실을 알 수 있습니다.

이 데이터를 차후 데이터 분석용으로 다루기 쉽게, ```ostype(clean)```과 ```osversion(clean)```이라는 두 개의 컬럼으로 분리하고 싶습니다. 가령 에를 들자면

  * ```osversion``` 컬럼값이 iOS11.4.1이라면, 새로운 컬럼인 ```ostype(clean)```에는 iOS가, ```osversion(clean)```에는 11.4.1이 들어가야 합니다.
  * ```osversion``` 컬럼값이 Android7.0이라면, 새로운 컬럼인 ```ostype(clean)```에는 Android가, ```osversion(clean)```에는 7.0이 들어가야 합니다.
  
최종적으로는 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>osversion</th>
            <th>ostype(clean)</th>
            <th>osversion(clean)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>iOS11.4.1</td>
            <td>iOS</td>
            <td>11.4.1</td>
        </tr>
        <tr>
            <th>1</th>
            <td>Android7.0</td>
            <td>Android</td>
            <td>7.0</td>
        </tr>
        <tr>
            <th>2</th>
            <td>iOS12.0</td>
            <td>iOS</td>
            <td>12.0</td>
        </tr>
        <tr>
            <th>3</th>
            <td>iOS11.4.1</td>
            <td>iOS</td>
            <td>11.4.1</td>
        </tr>
        <tr>
            <th>4</th>
            <td>iOS11.4.1</td>
            <td>iOS</td>
            <td>11.4.1</td>
        </tr>
    </tbody>
</table>

In [15]:
# Write your code here!
os =pd.DataFrame(raw_log['osversion'], columns =['osversion'])

In [16]:
os['osversion'].unique()

array(['iOS11.4.1', 'Android7.0', 'iOS12.0', 'Android8.0.0',
       'Android7.1.1', 'Android5.1.1', 'Android6.0.1', 'Android8.1.0',
       'iOS11.3.1', 'iOS11.4', 'iOS11.3', 'iOS10.0.1', 'iOS12.1',
       'Android4.4.2', 'Android6.0', 'Android5.0', 'iOS11.2.6',
       'iOS11.2.2', 'iOS10.3.2', 'Android5.0.2', 'iOS11.0', 'iOS11.0.3',
       'iOS11.2', 'iOS10.3.3', 'iOS11.1.2', 'iOS10.2.1', 'iOS10.0.2',
       'Android5.0.1', 'iOS10.1.1', 'iOS11.2.5', 'iOS11.2.1', 'iOS11.1.1',
       'Android7.1.2', 'Android4.4.4', 'iOS10.0.3', 'iOS11.0.2',
       'iOS10.1', 'iOS10.3.1', 'Android9', 'iOS10.2', 'iOS11.0.1',
       'iOS11.1', 'iOS10.3', 'Android5.1', 'Android4.1.2', 'Android4.3',
       'Android4.2.2'], dtype=object)

In [17]:
# fill in ostype(clean) with ios
os['ostype(clean)'] = 'iOS'
os['osversion(clean)'] = '11.4.1'

In [18]:
# insert Android if it has Android
os.loc[os['osversion'].str.contains("Android"), 'ostype(clean)'] = 'Android'

In [19]:
# get all android osversion
android = []
for name in os.loc[os['osversion'].str.contains("Android"), 'osversion']:
    android.append(name.split("Android")[1])
# get all iOS osversion
ios = []
for name in os.loc[os['osversion'].str.contains("iOS"), 'osversion']:
    ios.append(name.split("iOS")[1])

In [20]:
# insert Android Os Version 
os.loc[os['osversion'].str.contains("Android"), 'osversion(clean)'] = android

In [21]:
# insert Android Os Version 
os.loc[os['osversion'].str.contains("iOS"), 'osversion(clean)'] = ios

In [22]:
# Checking Os DataFrame
os.head()

    osversion ostype(clean) osversion(clean)
0   iOS11.4.1           iOS           11.4.1
1  Android7.0       Android              7.0
2     iOS12.0           iOS             12.0
3   iOS11.4.1           iOS           11.4.1
4   iOS11.4.1           iOS           11.4.1

**4. ```devicemanufacturer``` 컬럼 정보를 정리해주세요.**

```devicemanufacturer``` 컬럼은 사용자가 현재 사용하고 있는 스마트폰 디바이스를 제조한 제조사의 정보가 들어가 있습니다. 가령 ```samsung```이라고 적혀있으면 이 스마트폰은 삼성전자가 제조했다고 볼 수 있고, ```LG Electronics```라고 적혀있으면 이 스마트폰은 LG전자가 제조했다고 볼 수 있습니다. 

하지만 ```devicemanufacturer``` 컬럼에는 이 외에도 샤오미(Xiaomi), 폭스콘(Foxconn), 팬텍(PANTECH), 화웨이(HUAWEI)와 같은 마이너한 제조사 정보도 들어가 있습니다. 이 제조사들은 전체 사용자의 2%도 되지 않기 때문에, 이 데이터를 무시하거나 하나의 값(ex: Others)으로 통일해주면 데이터 분석가가 더 효율적으로 데이터를 분석할 수 있을 것 같습니다.

그러므로 ```devicemanufacturer``` 컬럼의 값을 정리해보겠습니다. 정리 방식은 다음과 같습니다.

 * ```samsung```이라고 적혀있는 값은 앞 글자를 대문자로 바꿉니다. (=```Samsung```)
 * ```LGE```와 ```LG Electronics```라는 값은 ```LG```로 통일합니다.
 * ```Apple```, ```Samsung```, ```LG```를 제외한 나머지는 ```Other```로 묶습니다.
 
최종적으로는 다음의 결과가 나와야 합니다.

  * Samsung - 230313
  * Apple - 163566
  * LG - 32649
  * Others - 7716

In [23]:
# Write your code here!
raw_log['devicemanufacturer'].value_counts()

samsung           230313
Apple             163566
LGE                32565
Xiaomi              3688
Foxconn             1248
PANTECH              706
HUAWEI               615
Google               417
Sony                 378
BlackBerry           185
TCL                  138
vivo                 122
LG Electronics        84
HOMTOM                60
OPPO                  34
asus                  28
CUBOT                 17
Huawei                17
HTC                   15
ZUK                   15
blackberry            13
SHARP                 12
UMIDIGI                8
Name: devicemanufacturer, dtype: int64

In [24]:
df_device=pd.DataFrame(raw_log['devicemanufacturer'])

In [25]:
# 1. samsung -> Samsung
df_device.loc[df_device['devicemanufacturer'].str.contains("samsung")] = "Samsung"

In [26]:
# 2. LGE와 LG Electronics라는 값은 LG로 통일합니다.
df_device.loc[df_device['devicemanufacturer'].str.contains("LG|LG E")] = "LG"

In [27]:
df_device.loc[-df_device['devicemanufacturer'].str.contains("LG|Apple|Samsung")] = "Others"

In [28]:
# Check the answer
df_device['devicemanufacturer'].value_counts()

Samsung    230313
Apple      163566
LG          32649
Others       7716
Name: devicemanufacturer, dtype: int64

**5. ```channel``` 컬럼 정보를 정리해주세요.**

```channel``` 컬럼을 사용자가 크몽 서비스에 유입된 경로를 기록한 정보입니다. 여기에는 웹(WEB), 구글(ex: google-play, google, google.adwords, etc), 네이버(ex: m_naver, m_naverpowercontents, pc_naver)등이 기록되어 있습니다. 이 정보도 마찬가지로 데이터를 분석하기 어렵게 산재되어 있기 때문에, 깔끔하게 정리해주고 싶습니다. 정리 방식은 다음과 같습니다.

  * 컬럼값에 google이라고 들어간 값(ex: google-play, google.adwords, etc)은 전부 google로 통일합니다.
  * 컬럼값에 daum이라고 들어간 값(ex: m_daum, etc)은 전부 daum으로 통일합니다.
  * 컬럼값이 naver라고 들어간 값(ex: m_naver, pc_naver, m_naverpowercontents, etc)은 전부 naver로 통일합니다.
  * 컬럼값에 apple이라고 들어간 값(ex: apple.searchads, etc)은 전부 apple로 통일합니다.
  * 컬럼값에 WEB이라고 들어간 값(ex: WEB)은 전부 web으로 통일합니다.
  
최종적으로는 다음의 결과가 나와야 합니다.

* unattributed - 270834
* web - 27639
* google - 27235
* (not set) - 2444
* naver - 1224
* daum - 966
* apple - 697
* facebook - 126

단, 여기서 ```channel``` 값에 빈 값(NaN, Not a Number)가 있다는 걸 주의하세요. 이 값은 소수점(float)으로 간주하기 때문에, 문자열에서 쓰이는 기능을 지원하지 않습니다. 이 점 주의해서 작성해주세요. (참고로 어떤 값이 빈 값(NaN)인지 아닌지를 구분하는 기능으로 판다스의 [isnull](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.isnull.html)을 사용하면 됩니다. 페이지의 Examples란을 살펴보세요)

In [29]:
# Write your code here!
raw_log['channel'].value_counts()

unattributed            270834
WEB                      27639
google-play              19973
google.adwords            4076
google                    3186
(not set)                 2444
m_daum                     966
m_naver                    849
apple.searchads            697
pc_naver                   227
m_naverpowercontents       148
facebook                   126
Name: channel, dtype: int64

In [30]:
df_channel = pd.DataFrame(raw_log['channel'])
df_channel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434244 entries, 0 to 434243
Data columns (total 1 columns):
channel    331165 non-null object
dtypes: object(1)
memory usage: 3.3+ MB

In [31]:
# there are null values: Null -> No
df_channel.loc[df_channel['channel'].isnull()] = "no"

In [32]:
df_channel.loc[df_channel['channel'].str.contains("google")] = "google"
df_channel.loc[df_channel['channel'].str.contains("m_daum")] = "daum"
df_channel.loc[df_channel['channel'].str.contains("m_naver|pc_naver|m_naverpowercontents")] = "naver"
df_channel.loc[df_channel['channel'].str.contains("apple.searchads")] = "apple"
df_channel.loc[df_channel['channel'].str.contains("WEB")] = 'web'

In [33]:
# fill nan back 
import numpy as np
df_channel.loc[df_channel['channel'].str.contains('no')] = np.nan

In [34]:
# check the answer 
df_channel['channel'].value_counts()

unattributed    270834
web              27639
google           27235
naver             1224
daum               966
apple              697
facebook           126
Name: channel, dtype: int64

**6. ```inappeventcategory``` 컬럼에 들어가 있는 정보를 여러 개의 컬럼으로 나눠주세요.**

```inappeventcategory```에는 사용자 액티비티를 나타내는 정보가 들어있습니다. 크몽에 방문한 고객이 상품 페이지를 보고 있는지, 구매를 진행중인지 등에 대한 정보가 이 컬럼에 담겨있다고 보시면 됩니다. 또한 ```inappeventcategory```에 있는 정보는 차후 퍼널(funnel) 데이터를 합치는데 사용되기도 합니다. 이 데이터를 정리해주세요. 정리 방식은 다음과 같습니다.

  * ```viewcategory``` - ```inappeventcategory```에서 언더바(_)를 기준으로 왼쪽 텍스트만 가져옵니다. 언더바가 없을 경우 점(.)의 왼쪽 텍스트만 가져옵니다.
  * ```viewid``` - ```inappeventcategory```에서 점(.)의 왼쪽 텍스트만 가져옵니다.
  * ```viewaction``` - ```inappeventcategory```에서 점(.)의 오른쪽 텍스트만 가져옵니다.

(팁: 파이썬에서 문자열을 나누는 기능인 [split](https://wikidocs.net/13#split)을 활용하면 생각보다 쉽게 문제를 풀 수 있습니다)
  
최종적으로는 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>inappeventcategory</th>
            <th>viewcategory</th>
            <th>viewid</th>
            <th>viewaction</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>home.view</td>
            <td>home</td>
            <td>home</td>
            <td>view</td>
        </tr>
        <tr>
            <th>1</th>
            <td>gig_detail.view</td>
            <td>gig</td>
            <td>gig_detail</td>
            <td>view</td>
        </tr>
        <tr>
            <th>2</th>
            <td>inbox_detail.view</td>
            <td>inbox</td>
            <td>inbox_detail</td>
            <td>view</td>
        </tr>
        <tr>
            <th>3</th>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>4</th>
            <td>buyer_order_track.view</td>
            <td>buyer</td>
            <td>buyer_order_track</td>
            <td>view</td>
        </tr>
    </tbody>
</table>

In [35]:
# Write your code here!
raw_log.columns

Index(['eventcategory', 'isfirstactivity', 'apppackagename', 'appversion',
       'devicetype', 'devicemanufacturer', 'osversion', 'userid', 'sourcetype',
       'channel', 'params_campaign', 'params_medium', 'params_term',
       'inappeventcategory', 'inappeventlabel', 'eventdatetime', 'rowuuid',
       'isfirstgoalactivity', 'event_rank'],
      dtype='object')

In [36]:
df_view = pd.DataFrame(raw_log['inappeventcategory'])

In [37]:
# null -> na
df_view.loc[df_view['inappeventcategory'].isnull()] = "no"

In [38]:
# creating view id and view action first
viewid = []
for name in df_view['inappeventcategory']:
    viewid.append(name.split("."))

In [39]:
viewid = pd.DataFrame(viewid, columns=['viewid', 'viewaction'])

In [40]:
# make viewcategory
viewcate = []
for name in viewid['viewid']:
    viewcate.append(name.split("_")[0])

In [41]:
df_view['viewcategory'] = viewcate
df_view["viewid"] = viewid['viewid']
df_view['viewcation'] = viewid['viewaction']

In [42]:
# back to null 
df_view.loc[df_view['inappeventcategory'].str.contains("no")] = np.nan

In [43]:
# Check the answer
df_view.head()

       inappeventcategory viewcategory             viewid viewcation
0               home.view         home               home       view
1         gig_detail.view          gig         gig_detail       view
2       inbox_detail.view        inbox       inbox_detail       view
3                     NaN          NaN                NaN        NaN
4  buyer_order_track.view        buyer  buyer_order_track       view

**7. 필요하지 않은 컬럼을 버려주세요.**

여기까지 했으면 대부분의 컬럼이 잘 정리된 것 같습니다. 이제 남은 것은 필요하지 않은 컬럼을 버리고, 기존 컬럼의 이름을 직관적으로 수정하는 일들만 남았습니다. 먼저 필요하지 않은 컬럼을 제거하겠습니다. 다음의 컬럼을 데이터에서 제거해주세요.

* ```osversion``` - 이제 이 컬럼을 버린 뒤 ```osversion(clean)```을 사용할 것입니다.
* ```devicemanufacturer``` - 이제 이 컬럼을 버린 뒤 ```devicemanufacturer(clean)```을 사용할 것입니다.
* ```canonicaldeviceuuid``` - 이제 이 컬럼을 버린 뒤 ```userid```를 사용할 것입니다.
* ```channel``` - 이제 이 컬럼을 버린 뒤 ```channel(clean)```을 사용할 것입니다.
* ```event_rank``` - 이 컬럼은 애초부터 사용할 필요가 없기 때문에 제거해줘도 됩니다.

최종적으로는 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>eventcategory</th>
            <th>isfirstactivity</th>
            <th>apppackagename</th>
            <th>appversion</th>
            <th>devicetype</th>
            <th>sourcetype</th>
            <th>params_campaign</th>
            <th>params_medium</th>
            <th>params_term</th>
            <th>inappeventcategory</th>
            <th>inappeventlabel</th>
            <th>eventdatetime</th>
            <th>rowuuid</th>
            <th>isfirstgoalactivity</th>
            <th>ostype(clean)</th>
            <th>osversion(clean)</th>
            <th>devicemanufacturer(clean)</th>
            <th>userid</th>
            <th>channel(clean)</th>
            <th>eventdatetime_year</th>
            <th>eventdatetime_month</th>
            <th>eventdatetime_day</th>
            <th>eventdatetime_hour</th>
            <th>eventdatetime_minute</th>
            <th>eventdatetime_second</th>
            <th>viewid</th>
            <th>viewaction</th>
            <th>viewcategory</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>goal</td>
            <td>False</td>
            <td>com.kmong.iOS</td>
            <td>4.0.4</td>
            <td>iPhone</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>home.view</td>
            <td>NaN</td>
            <td>2018-09-27 15:00:00</td>
            <td>fd2a188c-bc9b-4702-9c47-b546b2614817</td>
            <td>False</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>Apple</td>
            <td>F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957</td>
            <td>unattributed</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>home</td>
            <td>view</td>
            <td>home</td>
        </tr>
        <tr>
            <th>1</th>
            <td>goal</td>
            <td>False</td>
            <td>com.kmong.kmong</td>
            <td>3.3.5</td>
            <td>SM-N935S</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>gig_detail.view</td>
            <td>41201.0</td>
            <td>2018-09-27 15:00:00</td>
            <td>e62dccef-dd70-4415-8a33-c8324ddaed38</td>
            <td>False</td>
            <td>Android</td>
            <td>7.0</td>
            <td>Samsung</td>
            <td>8a871e50-0717-4aed-9bad-04ac3c3793be</td>
            <td>unattributed</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>gig_detail</td>
            <td>view</td>
            <td>gig</td>
        </tr>
        <tr>
            <th>2</th>
            <td>goal</td>
            <td>False</td>
            <td>com.kmong.iOS</td>
            <td>4.0.4</td>
            <td>iPhone</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>inbox_detail.view</td>
            <td>NaN</td>
            <td>2018-09-27 15:00:00</td>
            <td>14eb3197-db83-493a-b7be-83582960c40b</td>
            <td>False</td>
            <td>iOS</td>
            <td>12.0</td>
            <td>Apple</td>
            <td>A9E5778A-8F3D-4597-9718-74BF953A9F64</td>
            <td>unattributed</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>inbox_detail</td>
            <td>view</td>
            <td>inbox</td>
        </tr>
        <tr>
            <th>3</th>
            <td>foreground</td>
            <td>NaN</td>
            <td>com.kmong.iOS</td>
            <td>4.0.4</td>
            <td>iPhone</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>2018-09-27 15:00:01</td>
            <td>f9bb91af-248b-44dc-9f5c-1c00b37ea97b</td>
            <td>NaN</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>Apple</td>
            <td>168761CB-CB67-4592-867D-52780D651297</td>
            <td>NaN</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>1</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>4</th>
            <td>goal</td>
            <td>False</td>
            <td>com.kmong.iOS</td>
            <td>4.0.4</td>
            <td>iPhone</td>
            <td>viral</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>buyer_order_track.view</td>
            <td>NaN</td>
            <td>2018-09-27 15:00:02</td>
            <td>236e9946-7801-4898-b609-06c8ab1139dc</td>
            <td>False</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>Apple</td>
            <td>ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D</td>
            <td>web</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>2</td>
            <td>buyer_order_track</td>
            <td>view</td>
            <td>buyer</td>
        </tr>
    </tbody>
</table>

In [44]:
# Write your code here!
df = raw_log.drop(columns=['osversion', 'devicemanufacturer',"channel",'event_rank'])

In [45]:
len(df.columns)

15

**8. 이름을 통일성있게 변경해주세요.**

데이터를 분석할 때 컬럼명의 형식을 동일하게 유지하는 것이 중요합니다. 가령 회사 내부 데이터 팀에서 컬럼에서 두 개의 단어를 하이픈(-)으로 연결하기로 합의했다면 모든 컬럼을 하이픈으로 연결해야 하고, 언더바(_)로 연결하기로 합의했다면 모든 컬럼을 언더바로 연결해야 합니다.

하지만 아쉽게도, 현재 데이터의 컬럼명에는 이런 통일성이 잘 갖춰져 있는 것 같습니다. (ex: ```eventcategory``` vs ```params_term```) 그러므로 데이터의 컬럼명을 작성하는 형식을 하나로 통일하도록 하겠습니다. 이번 데이터에서 컬럼명을 짓는 방식은 다음과 같습니다.

  * 단어와 단어 사이는 언제나 언더바(_)로 구분합니다. 가령 하이픈(-)으로 구분하거나, 띄어쓰기를 사용하면 안 됩니다. (ex: event_category는 허용하지만, eventcategory나 event-category, 또는 event category는 허용하지 않습니다)
  * 컬럼명에 (clean)이라고 들어간 표현은 이제는 지워줘도 될 것 같습니다. (ex channel(clean) -> channel)

최종적으로는 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>event_category</th>
            <th>is_first_activity</th>
            <th>app_package_name</th>
            <th>app_version</th>
            <th>device_type</th>
            <th>source_type</th>
            <th>params_campaign</th>
            <th>params_medium</th>
            <th>params_term</th>
            <th>in_app_event_category</th>
            <th>in_app_event_label</th>
            <th>event_datetime</th>
            <th>row_uuid</th>
            <th>is_first_goal_activity</th>
            <th>os_type</th>
            <th>os_version</th>
            <th>device_manufacturer</th>
            <th>user_id</th>
            <th>channel</th>
            <th>event_datetime_year</th>
            <th>event_datetime_month</th>
            <th>event_datetime_day</th>
            <th>event_datetime_hour</th>
            <th>event_datetime_minute</th>
            <th>event_datetime_second</th>
            <th>view_id</th>
            <th>view_action</th>
            <th>view_category</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>goal</td>
            <td>False</td>
            <td>com.kmong.iOS</td>
            <td>4.0.4</td>
            <td>iPhone</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>home.view</td>
            <td>NaN</td>
            <td>2018-09-27 15:00:00</td>
            <td>fd2a188c-bc9b-4702-9c47-b546b2614817</td>
            <td>False</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>Apple</td>
            <td>F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957</td>
            <td>unattributed</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>home</td>
            <td>view</td>
            <td>home</td>
        </tr>
        <tr>
            <th>1</th>
            <td>goal</td>
            <td>False</td>
            <td>com.kmong.kmong</td>
            <td>3.3.5</td>
            <td>SM-N935S</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>gig_detail.view</td>
            <td>41201.0</td>
            <td>2018-09-27 15:00:00</td>
            <td>e62dccef-dd70-4415-8a33-c8324ddaed38</td>
            <td>False</td>
            <td>Android</td>
            <td>7.0</td>
            <td>Samsung</td>
            <td>8a871e50-0717-4aed-9bad-04ac3c3793be</td>
            <td>unattributed</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>gig_detail</td>
            <td>view</td>
            <td>gig</td>
        </tr>
        <tr>
            <th>2</th>
            <td>goal</td>
            <td>False</td>
            <td>com.kmong.iOS</td>
            <td>4.0.4</td>
            <td>iPhone</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>inbox_detail.view</td>
            <td>NaN</td>
            <td>2018-09-27 15:00:00</td>
            <td>14eb3197-db83-493a-b7be-83582960c40b</td>
            <td>False</td>
            <td>iOS</td>
            <td>12.0</td>
            <td>Apple</td>
            <td>A9E5778A-8F3D-4597-9718-74BF953A9F64</td>
            <td>unattributed</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>inbox_detail</td>
            <td>view</td>
            <td>inbox</td>
        </tr>
        <tr>
            <th>3</th>
            <td>foreground</td>
            <td>NaN</td>
            <td>com.kmong.iOS</td>
            <td>4.0.4</td>
            <td>iPhone</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>2018-09-27 15:00:01</td>
            <td>f9bb91af-248b-44dc-9f5c-1c00b37ea97b</td>
            <td>NaN</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>Apple</td>
            <td>168761CB-CB67-4592-867D-52780D651297</td>
            <td>NaN</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>1</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>4</th>
            <td>goal</td>
            <td>False</td>
            <td>com.kmong.iOS</td>
            <td>4.0.4</td>
            <td>iPhone</td>
            <td>viral</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>buyer_order_track.view</td>
            <td>NaN</td>
            <td>2018-09-27 15:00:02</td>
            <td>236e9946-7801-4898-b609-06c8ab1139dc</td>
            <td>False</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>Apple</td>
            <td>ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D</td>
            <td>web</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>2</td>
            <td>buyer_order_track</td>
            <td>view</td>
            <td>buyer</td>
        </tr>
    </tbody>
</table>

In [199]:
# Write your code here!

In [46]:
# datetime 
a=df_datetime
for name in a.columns:
    df[name] = a[name]

In [48]:
# os
a = os.drop(columns='osversion')
for name in a.columns:
    df[name] = a[name]

In [49]:
# device
df['devicemanufacturer'] = df_device['devicemanufacturer']

In [50]:
# channel
df['channel'] = df_channel['channel']

In [51]:
# inappeventcategory
a=df_view.drop(columns='inappeventcategory')
for name in a.columns:
    df[name] = a[name]

In [53]:
# check the answer 
df.columns

Index(['eventcategory', 'isfirstactivity', 'apppackagename', 'appversion',
       'devicetype', 'userid', 'sourcetype', 'params_campaign',
       'params_medium', 'params_term', 'inappeventcategory', 'inappeventlabel',
       'eventdatetime', 'rowuuid', 'isfirstgoalactivity', 'eventdatetime_year',
       'eventdatetime_month', 'eventdatetime_day', 'eventdatetime_hour',
       'eventdatetime_minute', 'eventdatetime_second', 'ostype(clean)',
       'osversion(clean)', 'devicemanufacturer', 'channel', 'viewcategory',
       'viewid', 'viewcation'],
      dtype='object')

**9. 컬럼을 정렬해주세요.**

마지막은 컬럼을 용도에 맞게 잘 정렬해주면 될 것 같습니다. 정렬할 때는 보통 1) 중요한 컬럼을 좌측으로, 상대적으로 중요하지 않은 컬럼을 우측으로 옮겨주고, 2) 비슷한 역할을 하는 컬럼이나 서로간에 연관되어있는 컬럼은 같은 위치로 묶어줍니다. 최종적으로는 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>row_uuid</th>
            <th>app_package_name</th>
            <th>user_id</th>
            <th>event_datetime</th>
            <th>event_datetime_year</th>
            <th>event_datetime_month</th>
            <th>event_datetime_day</th>
            <th>event_datetime_hour</th>
            <th>event_datetime_minute</th>
            <th>event_datetime_second</th>
            <th>device_manufacturer</th>
            <th>device_type</th>
            <th>os_type</th>
            <th>os_version</th>
            <th>app_version</th>
            <th>event_category</th>
            <th>view_category</th>
            <th>view_id</th>
            <th>view_action</th>
            <th>in_app_event_category</th>
            <th>in_app_event_label</th>
            <th>source_type</th>
            <th>channel</th>
            <th>params_campaign</th>
            <th>params_medium</th>
            <th>params_term</th>
            <th>is_first_activity</th>
            <th>is_first_goal_activity</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>fd2a188c-bc9b-4702-9c47-b546b2614817</td>
            <td>com.kmong.iOS</td>
            <td>F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>home</td>
            <td>home</td>
            <td>view</td>
            <td>home.view</td>
            <td>NaN</td>
            <td>unattributed</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
        </tr>
        <tr>
            <th>1</th>
            <td>e62dccef-dd70-4415-8a33-c8324ddaed38</td>
            <td>com.kmong.kmong</td>
            <td>8a871e50-0717-4aed-9bad-04ac3c3793be</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Samsung</td>
            <td>SM-N935S</td>
            <td>Android</td>
            <td>7.0</td>
            <td>3.3.5</td>
            <td>goal</td>
            <td>gig</td>
            <td>gig_detail</td>
            <td>view</td>
            <td>gig_detail.view</td>
            <td>41201.0</td>
            <td>unattributed</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
        </tr>
        <tr>
            <th>2</th>
            <td>14eb3197-db83-493a-b7be-83582960c40b</td>
            <td>com.kmong.iOS</td>
            <td>A9E5778A-8F3D-4597-9718-74BF953A9F64</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>12.0</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>inbox</td>
            <td>inbox_detail</td>
            <td>view</td>
            <td>inbox_detail.view</td>
            <td>NaN</td>
            <td>unattributed</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
        </tr>
        <tr>
            <th>3</th>
            <td>f9bb91af-248b-44dc-9f5c-1c00b37ea97b</td>
            <td>com.kmong.iOS</td>
            <td>168761CB-CB67-4592-867D-52780D651297</td>
            <td>2018-09-27 15:00:01</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>1</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>foreground</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>4</th>
            <td>236e9946-7801-4898-b609-06c8ab1139dc</td>
            <td>com.kmong.iOS</td>
            <td>ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D</td>
            <td>2018-09-27 15:00:02</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>2</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>buyer</td>
            <td>buyer_order_track</td>
            <td>view</td>
            <td>buyer_order_track.view</td>
            <td>NaN</td>
            <td>viral</td>
            <td>web</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
        </tr>
    </tbody>
</table>

In [54]:
# Write your code here!
df_ex = df

In [55]:
df_ex.columns =['event_category', 'is_first_activity', 'app_package_name', 'app_version',
       'device_type', 'user_id', 'source_type', 'params_campaign',
       'params_medium', 'params_term', 'in_app_event_category', 'in_app_event_label',
       'event_datetime', 'row_uuid', 'is_first_goal_activity', 'event_datetime_year',
       'event_datetime_month', 'event_datetime_day', 'event_datetime_hour',
       'event_datetime_minute', 'event_datetime_second', 'os_type', 'os_version', 'device_manufacturer', 'channel',
       'view_category', 'view_id', 'view_action']
df_ex.columns

Index(['event_category', 'is_first_activity', 'app_package_name',
       'app_version', 'device_type', 'user_id', 'source_type',
       'params_campaign', 'params_medium', 'params_term',
       'in_app_event_category', 'in_app_event_label', 'event_datetime',
       'row_uuid', 'is_first_goal_activity', 'event_datetime_year',
       'event_datetime_month', 'event_datetime_day', 'event_datetime_hour',
       'event_datetime_minute', 'event_datetime_second', 'os_type',
       'os_version', 'device_manufacturer', 'channel', 'view_category',
       'view_id', 'view_action'],
      dtype='object')

In [56]:
new_columns = ['row_uuid', 'app_package_name', 'user_id', 'event_datetime', 'event_datetime_year', 
               'event_datetime_month', 'event_datetime_day', 'event_datetime_hour','event_datetime_minute',
               'event_datetime_second', 'device_manufacturer',
               'device_type','os_type','os_version','app_version','event_category','view_category','view_id',
               'view_action','in_app_event_category','in_app_event_label','source_type','channel','params_campaign',
               'params_medium','params_term','is_first_activity','is_first_goal_activity']

In [57]:
len(new_columns)

28

In [58]:
df_ex=df_ex.reindex_axis(new_columns, axis=1)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
  """Entry point for launching an IPython kernel.

In [59]:
df_ex.head()

,row_uuid,app_package_name,user_id,event_datetime,event_datetime_year,event_datetime_month,event_datetime_day,event_datetime_hour,event_datetime_minute,event_datetime_second,device_manufacturer,device_type,os_type,os_version,app_version,event_category,view_category,view_id,view_action,in_app_event_category,in_app_event_label,source_type,channel,params_campaign,params_medium,params_term,is_first_activity,is_first_goal_activity
0,fd2a188c-bc9b-4702-9c47-b546b2614817,com.kmong.iOS,F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,11.4.1,4.0.4,goal,home,home,view,home.view,NaN,unattributed,unattributed,NaN,NaN,NaN,False,False
1,e62dccef-dd70-4415-8a33-c8324ddaed38,com.kmong.kmong,8a871e50-0717-4aed-9bad-04ac3c3793be,2018-09-28 00:00:00,2018,9,28,0,0,0,Samsung,SM-N935S,Android,7.0,3.3.5,goal,gig,gig_detail,view,gig_detail.view,41201.0,unattributed,unattributed,NaN,NaN,NaN,False,False
2,14eb3197-db83-493a-b7be-83582960c40b,com.kmong.iOS,A9E5778A-8F3D-4597-9718-74BF953A9F64,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,12.0,4.0.4,goal,inbox,inbox_detail,view,inbox_detail.view,NaN,unattributed,unattributed,NaN,NaN,NaN,False,False
3,f9bb91af-248b-44dc-9f5c-1c00b37ea97b,com.kmong.iOS,168761CB-CB67-4592-867D-52780D651297,2018-09-28 00:00:01,2018,9,28,0,0,1,Apple,iPhone,iOS,11.4.1,4.0.4,foreground,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,236e9946-7801-4898-b609-06c8ab1139dc,com.kmong.iOS,ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D,2018-09-28 00:00:02,2018,9,28,0,0,2,Apple,iPhone,iOS,11.4.1,4.0.4,goal,buyer,buyer_order_track,view,buyer_order_track.view,NaN,viral,web,NaN,NaN,NaN,False,False

**10. funnel 데이터를 정리해주세요.**

다음으로는 퍼널(funnel) 데이터를 정리하겠습니다. 퍼널 데이터에는 크몽 서비스에서 사용하는 퍼널에 대한 부연 설명을 담고 있습니다. 기쁘게도 이 데이터는 잘 정리되어 있기 때문에, 별도로 처리해줘야 하는 건 많지 않습니다. 다음의 설명을 참고하여 데이터를 정리해주세요.

  1. 먼저 컬럼을 ```Lv1```, ```Lv2```, ```viewid```, ```viewid desc```, ```funnel name```, ```funnel desc``` 순으로 정렬해주세요.
  2. 그 다음 모든 컬럼을 소문자로 통일하고(ex: Lv1 -> lv1), 띄어쓰기를 언더바(_)로 바꿔주세요. (ex: funnel name -> funnel_name)
  
최종적으로는 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>lv1</th>
            <th>lv2</th>
            <th>view_id</th>
            <th>view_desc</th>
            <th>funnel_name</th>
            <th>funnel_desc</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>11</td>
            <td>1100</td>
            <td>home</td>
            <td>홈 (탭)</td>
            <td>home</td>
            <td>홈</td>
        </tr>
        <tr>
            <th>1</th>
            <td>12</td>
            <td>1210</td>
            <td>category_list</td>
            <td>카테고리 목록 (탭)</td>
            <td>category</td>
            <td>카테고리</td>
        </tr>
        <tr>
            <th>2</th>
            <td>12</td>
            <td>1200</td>
            <td>category_gig</td>
            <td>카테고리-상품목록</td>
            <td>category</td>
            <td>카테고리</td>
        </tr>
        <tr>
            <th>3</th>
            <td>13</td>
            <td>1300</td>
            <td>search</td>
            <td>검색</td>
            <td>search</td>
            <td>검색</td>
        </tr>
        <tr>
            <th>4</th>
            <td>13</td>
            <td>1301</td>
            <td>search_gig</td>
            <td>검색-상품목록</td>
            <td>search</td>
            <td>검색</td>
        </tr>
    </tbody>
</table>

In [60]:
# Write your code here!
df_funnel = raw_funnel
new_columns = ["lv1","lv2", "view_id","view_desc","funnel_name","funnel_desc"]
df_funnel.columns = ['lv2', 'view_id', 'view_desc', 'lv1', 'funnel_name', 'funnel_desc']
df_funnel.columns

Index(['lv2', 'view_id', 'view_desc', 'lv1', 'funnel_name', 'funnel_desc'], dtype='object')

In [61]:
df_funnel = df_funnel.reindex_axis(new_columns, axis=1)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
  """Entry point for launching an IPython kernel.

In [62]:
df_funnel.head()

   lv1   lv2        view_id    view_desc funnel_name funnel_desc
0   11  1100           home        홈 (탭)        home           홈
1   12  1210  category_list  카테고리 목록 (탭)    category        카테고리
2   12  1200   category_gig    카테고리-상품목록    category        카테고리
3   13  1300         search           검색      search          검색
4   13  1301     search_gig      검색-상품목록      search          검색

**11. category 데이터를 정리해주세요.**

퍼널(funnel) 데이터와 마찬가지로, category 데이터도 정리하겠습니다. category 데이터는크몽에서 판매하는 상품의 카테고리를 나타내는 정보인데, 퍼널 데이터와 마찬가지로 이 데이터로 잘 정리되어 있기 때문에 크게 건드려줘야 하는 부분은 없고, 컬럼명만 바꿔주면 될 것 같습니다. 다음의 기준을 참고하여 컬럼명을 사정해주세요.

* 단어 사이에는 언더바(```_```)를 붙입니다. (ex: categoryid -> category_id)
* 축약어는 전체 단어로 풀어서 작성합니다. (ex: cat1 -> category1)
  
최종적으로는 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>depth</th>
            <th>category_id</th>
            <th>category_name</th>
            <th>category1_id</th>
            <th>category2_id</th>
            <th>category3_id</th>
            <th>category1</th>
            <th>category2</th>
            <th>category3</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>1</td>
            <td>1</td>
            <td>디자인</td>
            <td>1</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>디자인</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>1</th>
            <td>1</td>
            <td>2</td>
            <td>마케팅</td>
            <td>2</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>마케팅</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>2</th>
            <td>1</td>
            <td>3</td>
            <td>번역·통역</td>
            <td>3</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>번역·통역</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>3</th>
            <td>1</td>
            <td>4</td>
            <td>문서작성</td>
            <td>4</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>문서작성</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>4</th>
            <td>1</td>
            <td>6</td>
            <td>IT·프로그래밍</td>
            <td>6</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>IT·프로그래밍</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
    </tbody>
</table>

In [63]:
# Write your code here!
df_category = raw_category

In [64]:
df_category.columns = ['depth', 'category_id', 'category_name', 'category1_id', 'category2_id', 'categoryt3_id',
       'category1', 'category2', 'category3']

In [65]:
df_category.head()

,depth,category_id,category_name,category1_id,category2_id,categoryt3_id,category1,category2,category3
0,1,1,디자인,1,NaN,NaN,디자인,NaN,NaN
1,1,2,마케팅,2,NaN,NaN,마케팅,NaN,NaN
2,1,3,번역·통역,3,NaN,NaN,번역·통역,NaN,NaN
3,1,4,문서작성,4,NaN,NaN,문서작성,NaN,NaN
4,1,6,IT·프로그래밍,6,NaN,NaN,IT·프로그래밍,NaN,NaN

### 세 개의 데이터를 하나로 합치기

이번에는 수정한 ```log```, ```funnel```, ```category``` 데이터를 하나로 합쳐보겠습니다. 이 부분은 다소 난이도가 높기 때문에, 적극적으로 구글을 검색하거나 다른 자료를 참고하는 것을 추천드립니다. 특히나 [Merge, join, and concatenate](https://pandas.pydata.org/pandas-docs/stable/merging.html) 자료를 한 번 살펴보신 뒤 아래 문제를 시도한다면 더 쉽게 문제를 풀 수 있을 것입니다.

**12. ```log``` 데이터의 view_id 컬럼과 ```funnel``` 데이터의 view_id 컬럼을 활용하여 두 개의 데이터를 합쳐주세요**

앞서 설명드린대로 ```log``` 데이터에 사용자의 액티비티가 모두 모여져있고, 여기에서 가장 중요한 정보 중 하나인 퍼널(funnel)에 대한 부연 설명이 ```funnel``` 데이터에 모여 있습니다. 그러므로 이 두개를 합친다면, 차후에 ```log```데이터에서 퍼널 분석을 할 때 다른 데이터 분석가들이 더 직관적으로 데이터를 이해할 수 있을 것 같습니다.

그러므로 두 개의 데이터를 합쳐주세요. 두 개의 데이터와 연관이 있는 컬럼은 ```view_id```라는 이름의 컬럼이며, 데이터를 합칠 때는 [merge](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html)라는 함수를 잘 사용하면 생각보다 쉽게 데이터를 합칠 수 있습니다. 또한 합칠 때 ```log``` 데이터는 누락되지 않고 전부 살아있어야 하며, ```funnel```데이터는 ```log```데이터에 일치하는 것만 살리고 나머지는 지워져도 상관 없습니다. (이를 전문 용어로 **left merge**라고 합니다)

최종적으로는 다음의 결과가 나와야 합니다. (```log``` 데이터와 동일해보이지만 자세히 보시면 오른쪽에 ```funnel``` 데이터가 추가되어 있습니다)

<table border="1" class="dataframe">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>row_uuid</th>
            <th>app_package_name</th>
            <th>user_id</th>
            <th>event_datetime</th>
            <th>event_datetime_year</th>
            <th>event_datetime_month</th>
            <th>event_datetime_day</th>
            <th>event_datetime_hour</th>
            <th>event_datetime_minute</th>
            <th>event_datetime_second</th>
            <th>device_manufacturer</th>
            <th>device_type</th>
            <th>os_type</th>
            <th>os_version</th>
            <th>app_version</th>
            <th>event_category</th>
            <th>view_category</th>
            <th>view_id</th>
            <th>view_action</th>
            <th>in_app_event_category</th>
            <th>in_app_event_label</th>
            <th>source_type</th>
            <th>channel</th>
            <th>params_campaign</th>
            <th>params_medium</th>
            <th>params_term</th>
            <th>is_first_activity</th>
            <th>is_first_goal_activity</th>
            <th>lv1</th>
            <th>lv2</th>
            <th>view_desc</th>
            <th>funnel_name</th>
            <th>funnel_desc</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>fd2a188c-bc9b-4702-9c47-b546b2614817</td>
            <td>com.kmong.iOS</td>
            <td>F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>home</td>
            <td>home</td>
            <td>view</td>
            <td>home.view</td>
            <td>NaN</td>
            <td>unattributed</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
            <td>11.0</td>
            <td>1100.0</td>
            <td>홈 (탭)</td>
            <td>home</td>
            <td>홈</td>
        </tr>
        <tr>
            <th>1</th>
            <td>e62dccef-dd70-4415-8a33-c8324ddaed38</td>
            <td>com.kmong.kmong</td>
            <td>8a871e50-0717-4aed-9bad-04ac3c3793be</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Samsung</td>
            <td>SM-N935S</td>
            <td>Android</td>
            <td>7.0</td>
            <td>3.3.5</td>
            <td>goal</td>
            <td>gig</td>
            <td>gig_detail</td>
            <td>view</td>
            <td>gig_detail.view</td>
            <td>41201.0</td>
            <td>unattributed</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
            <td>14.0</td>
            <td>1400.0</td>
            <td>상품상세</td>
            <td>gig</td>
            <td>상품</td>
        </tr>
        <tr>
            <th>2</th>
            <td>14eb3197-db83-493a-b7be-83582960c40b</td>
            <td>com.kmong.iOS</td>
            <td>A9E5778A-8F3D-4597-9718-74BF953A9F64</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>12.0</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>inbox</td>
            <td>inbox_detail</td>
            <td>view</td>
            <td>inbox_detail.view</td>
            <td>NaN</td>
            <td>unattributed</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
            <td>16.0</td>
            <td>1610.0</td>
            <td>메시지목록-상세</td>
            <td>inbox</td>
            <td>메시지</td>
        </tr>
        <tr>
            <th>3</th>
            <td>f9bb91af-248b-44dc-9f5c-1c00b37ea97b</td>
            <td>com.kmong.iOS</td>
            <td>168761CB-CB67-4592-867D-52780D651297</td>
            <td>2018-09-27 15:00:01</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>1</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>foreground</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>4</th>
            <td>236e9946-7801-4898-b609-06c8ab1139dc</td>
            <td>com.kmong.iOS</td>
            <td>ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D</td>
            <td>2018-09-27 15:00:02</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>2</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>buyer</td>
            <td>buyer_order_track</td>
            <td>view</td>
            <td>buyer_order_track.view</td>
            <td>NaN</td>
            <td>viral</td>
            <td>web</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
            <td>24.0</td>
            <td>2410.0</td>
            <td>메뉴목록-구매관리-거래메시지</td>
            <td>transaction_history</td>
            <td>거래관리</td>
        </tr>
    </tbody>
</table>

In [277]:
# Write your code here!

In [66]:
df_funnel.columns
# both have view id !! it can be key !!

Index(['lv1', 'lv2', 'view_id', 'view_desc', 'funnel_name', 'funnel_desc'], dtype='object')

In [67]:
# left join: Add data only share view_id to df!! 
df_ex=df_ex.merge(df_funnel, how='left', on = "view_id")

In [68]:
df_ex.head()

,row_uuid,app_package_name,user_id,event_datetime,event_datetime_year,event_datetime_month,event_datetime_day,event_datetime_hour,event_datetime_minute,event_datetime_second,device_manufacturer,device_type,os_type,os_version,app_version,event_category,view_category,view_id,view_action,in_app_event_category,in_app_event_label,source_type,channel,params_campaign,params_medium,params_term,is_first_activity,is_first_goal_activity,lv1,lv2,view_desc,funnel_name,funnel_desc
0,fd2a188c-bc9b-4702-9c47-b546b2614817,com.kmong.iOS,F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,11.4.1,4.0.4,goal,home,home,view,home.view,NaN,unattributed,unattributed,NaN,NaN,NaN,False,False,11.0,1100.0,홈 (탭),home,홈
1,e62dccef-dd70-4415-8a33-c8324ddaed38,com.kmong.kmong,8a871e50-0717-4aed-9bad-04ac3c3793be,2018-09-28 00:00:00,2018,9,28,0,0,0,Samsung,SM-N935S,Android,7.0,3.3.5,goal,gig,gig_detail,view,gig_detail.view,41201.0,unattributed,unattributed,NaN,NaN,NaN,False,False,14.0,1400.0,상품상세,gig,상품
2,14eb3197-db83-493a-b7be-83582960c40b,com.kmong.iOS,A9E5778A-8F3D-4597-9718-74BF953A9F64,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,12.0,4.0.4,goal,inbox,inbox_detail,view,inbox_detail.view,NaN,unattributed,unattributed,NaN,NaN,NaN,False,False,16.0,1610.0,메시지목록-상세,inbox,메시지
3,f9bb91af-248b-44dc-9f5c-1c00b37ea97b,com.kmong.iOS,168761CB-CB67-4592-867D-52780D651297,2018-09-28 00:00:01,2018,9,28,0,0,1,Apple,iPhone,iOS,11.4.1,4.0.4,foreground,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,236e9946-7801-4898-b609-06c8ab1139dc,com.kmong.iOS,ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D,2018-09-28 00:00:02,2018,9,28,0,0,2,Apple,iPhone,iOS,11.4.1,4.0.4,goal,buyer,buyer_order_track,view,buyer_order_track.view,NaN,viral,web,NaN,NaN,NaN,False,False,24.0,2410.0,메뉴목록-구매관리-거래메시지,transaction_history,거래관리

**13. 12번 데이터의 ```in_app_event_label``` 컬럼과 ```category``` 데이터의 ```category_id``` 컬럼을 활용하여 두 개의 데이터를 합쳐주세요.**

퍼널(funnel)과 마찬가지로 ```category``` 데이터도 하나로 합쳐보겠습니다.

이것도 12번 데이터와 마찬가지로 판다스(Pandas)의 [merge](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html), 그것도 **left merge**를 사용하면 됩니다. 다만 두 데이터가 ```view_id```라는 공통의 컬럼을 보유하고 있던 이전과는 다르게, 이번에는 12번 데이터에는 ```in_app_event_label``` 컬럼이, ```category``` 데이터에는 ```category_id``` 컬럼이 서로 연관이 있습니다. 이 컬럼을 사용하여 두 개를 합쳐주세요.

최종적으로는 다음의 결과가 나와야 합니다. (자세히 보시면 오른쪽에 ```category_id``` 데이터가 추가되어 있습니다)

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>row_uuid</th>
            <th>app_package_name</th>
            <th>user_id</th>
            <th>event_datetime</th>
            <th>event_datetime_year</th>
            <th>event_datetime_month</th>
            <th>event_datetime_day</th>
            <th>event_datetime_hour</th>
            <th>event_datetime_minute</th>
            <th>event_datetime_second</th>
            <th>device_manufacturer</th>
            <th>device_type</th>
            <th>os_type</th>
            <th>os_version</th>
            <th>app_version</th>
            <th>event_category</th>
            <th>view_category</th>
            <th>view_id</th>
            <th>view_action</th>
            <th>in_app_event_category</th>
            <th>in_app_event_label</th>
            <th>source_type</th>
            <th>channel</th>
            <th>params_campaign</th>
            <th>params_medium</th>
            <th>params_term</th>
            <th>is_first_activity</th>
            <th>is_first_goal_activity</th>
            <th>lv1</th>
            <th>lv2</th>
            <th>view_desc</th>
            <th>funnel_name</th>
            <th>funnel_desc</th>
            <th>depth</th>
            <th>category_id</th>
            <th>category_name</th>
            <th>category1_id</th>
            <th>category2_id</th>
            <th>category3_id</th>
            <th>category1</th>
            <th>category2</th>
            <th>category3</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>fd2a188c-bc9b-4702-9c47-b546b2614817</td>
            <td>com.kmong.iOS</td>
            <td>F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>home</td>
            <td>home</td>
            <td>view</td>
            <td>home.view</td>
            <td>NaN</td>
            <td>unattributed</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
            <td>11.0</td>
            <td>1100.0</td>
            <td>홈 (탭)</td>
            <td>home</td>
            <td>홈</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>1</th>
            <td>e62dccef-dd70-4415-8a33-c8324ddaed38</td>
            <td>com.kmong.kmong</td>
            <td>8a871e50-0717-4aed-9bad-04ac3c3793be</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Samsung</td>
            <td>SM-N935S</td>
            <td>Android</td>
            <td>7.0</td>
            <td>3.3.5</td>
            <td>goal</td>
            <td>gig</td>
            <td>gig_detail</td>
            <td>view</td>
            <td>gig_detail.view</td>
            <td>41201.0</td>
            <td>unattributed</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
            <td>14.0</td>
            <td>1400.0</td>
            <td>상품상세</td>
            <td>gig</td>
            <td>상품</td>
            <td>3.0</td>
            <td>41201.0</td>
            <td>자기소개서</td>
            <td>4.0</td>
            <td>412.0</td>
            <td>41201.0</td>
            <td>문서작성</td>
            <td>자기소개서·이력서</td>
            <td>자기소개서</td>
        </tr>
        <tr>
            <th>2</th>
            <td>14eb3197-db83-493a-b7be-83582960c40b</td>
            <td>com.kmong.iOS</td>
            <td>A9E5778A-8F3D-4597-9718-74BF953A9F64</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>12.0</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>inbox</td>
            <td>inbox_detail</td>
            <td>view</td>
            <td>inbox_detail.view</td>
            <td>NaN</td>
            <td>unattributed</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
            <td>16.0</td>
            <td>1610.0</td>
            <td>메시지목록-상세</td>
            <td>inbox</td>
            <td>메시지</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>3</th>
            <td>f9bb91af-248b-44dc-9f5c-1c00b37ea97b</td>
            <td>com.kmong.iOS</td>
            <td>168761CB-CB67-4592-867D-52780D651297</td>
            <td>2018-09-27 15:00:01</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>1</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>foreground</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>4</th>
            <td>236e9946-7801-4898-b609-06c8ab1139dc</td>
            <td>com.kmong.iOS</td>
            <td>ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D</td>
            <td>2018-09-27 15:00:02</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>2</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>buyer</td>
            <td>buyer_order_track</td>
            <td>view</td>
            <td>buyer_order_track.view</td>
            <td>NaN</td>
            <td>viral</td>
            <td>web</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
            <td>24.0</td>
            <td>2410.0</td>
            <td>메뉴목록-구매관리-거래메시지</td>
            <td>transaction_history</td>
            <td>거래관리</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
    </tbody>
</table>

In [69]:
# Write your code here!
# create key!! 
df_category['in_app_event_label'] = df_category['category_id']

In [70]:
df_ex=df_ex.merge(df_category, how='left', on = 'in_app_event_label')

In [71]:
df_ex.head()

,row_uuid,app_package_name,user_id,event_datetime,event_datetime_year,event_datetime_month,event_datetime_day,event_datetime_hour,event_datetime_minute,event_datetime_second,device_manufacturer,device_type,os_type,os_version,app_version,event_category,view_category,view_id,view_action,in_app_event_category,in_app_event_label,source_type,channel,params_campaign,params_medium,params_term,is_first_activity,is_first_goal_activity,lv1,lv2,view_desc,funnel_name,funnel_desc,depth,category_id,category_name,category1_id,category2_id,categoryt3_id,category1,category2,category3
0,fd2a188c-bc9b-4702-9c47-b546b2614817,com.kmong.iOS,F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,11.4.1,4.0.4,goal,home,home,view,home.view,NaN,unattributed,unattributed,NaN,NaN,NaN,False,False,11.0,1100.0,홈 (탭),home,홈,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,e62dccef-dd70-4415-8a33-c8324ddaed38,com.kmong.kmong,8a871e50-0717-4aed-9bad-04ac3c3793be,2018-09-28 00:00:00,2018,9,28,0,0,0,Samsung,SM-N935S,Android,7.0,3.3.5,goal,gig,gig_detail,view,gig_detail.view,41201.0,unattributed,unattributed,NaN,NaN,NaN,False,False,14.0,1400.0,상품상세,gig,상품,3.0,41201.0,자기소개서,4.0,412.0,41201.0,문서작성,자기소개서·이력서,자기소개서
2,14eb3197-db83-493a-b7be-83582960c40b,com.kmong.iOS,A9E5778A-8F3D-4597-9718-74BF953A9F64,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,12.0,4.0.4,goal,inbox,inbox_detail,view,inbox_detail.view,NaN,unattributed,unattributed,NaN,NaN,NaN,False,False,16.0,1610.0,메시지목록-상세,inbox,메시지,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f9bb91af-248b-44dc-9f5c-1c00b37ea97b,com.kmong.iOS,168761CB-CB67-4592-867D-52780D651297,2018-09-28 00:00:01,2018,9,28,0,0,1,Apple,iPhone,iOS,11.4.1,4.0.4,foreground,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,236e9946-7801-4898-b609-06c8ab1139dc,com.kmong.iOS,ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D,2018-09-28 00:00:02,2018,9,28,0,0,2,Apple,iPhone,iOS,11.4.1,4.0.4,goal,buyer,buyer_order_track,view,buyer_order_track.view,NaN,viral,web,NaN,NaN,NaN,False,False,24.0,2410.0,메뉴목록-구매관리-거래메시지,transaction_history,거래관리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**14. 합친 데이터에서 필요하지 않은 컬럼은 버려주고 정렬해주세요.**

이제 데이터를 다 정리하고 합쳤으면, 나머지는 분석에 필요하지 않은 데이터를 버려주는 일만 남았습니다. 실제 회사에서는 데이터를 처음 읽을 때 굉장히 많은 컬럼을 읽어오게 되는데, 이를 전부 읽어와 분석하지 않고 1) 필요하지 않은 컬럼은 사전에 버려주고, 2) 남은 데이터에서 분석할 때 필요한 데이터만 그때그때 가져오는 습관을 드리는 것이 좋습니다.

그러므로 다음의 컬럼은 사용하지 않을 예정이니 데이터에서 삭제하도록 하겠습니다.

  * ```in_app_event_category```
  * ```in_app_event_label```
  * ```source_type```
  * ```Lv1```, ```Lv2```
  * ```funnel_name```, ```depth```
  * ```category_id```, ```category1_id```, ```category2_id```, ```category3_id```

또한 여기에서 다음의 순서대로 데이터를 정렬해주세요.

  * ```row_uuid```
  * ```app_package_name```
  * ```user_id```
  * ```event_datetime```
  * ```event_datetime_year```
  * ```event_datetime_month```
  * ```event_datetime_day```
  * ```event_datetime_hour```
  * ```event_datetime_minute```
  * ```event_datetime_second```
  * ```device_manufacturer```
  * ```device_type```
  * ```os_type```
  * ```os_version```
  * ```app_version```
  * ```event_category```
  * ```view_category```
  * ```view_id```
  * ```view_action```
  * ```funnel_desc```
  * ```view_desc```
  * ```category_name```
  * ```category1```
  * ```category2```
  * ```category3```
  * ```channel```
  * ```params_campaign```
  * ```params_medium```
  * ```params_term```
  * ```is_first_activity```
  * ```is_first_goal_activity```
  
최종적으로는 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe" style="float: left;">
    <thead>
        <tr style="text-align: right;">
            <th></th>
            <th>row_uuid</th>
            <th>app_package_name</th>
            <th>user_id</th>
            <th>event_datetime</th>
            <th>event_datetime_year</th>
            <th>event_datetime_month</th>
            <th>event_datetime_day</th>
            <th>event_datetime_hour</th>
            <th>event_datetime_minute</th>
            <th>event_datetime_second</th>
            <th>device_manufacturer</th>
            <th>device_type</th>
            <th>os_type</th>
            <th>os_version</th>
            <th>app_version</th>
            <th>event_category</th>
            <th>view_category</th>
            <th>view_id</th>
            <th>view_action</th>
            <th>funnel_desc</th>
            <th>view_desc</th>
            <th>category_name</th>
            <th>category1</th>
            <th>category2</th>
            <th>category3</th>
            <th>channel</th>
            <th>params_campaign</th>
            <th>params_medium</th>
            <th>params_term</th>
            <th>is_first_activity</th>
            <th>is_first_goal_activity</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>0</th>
            <td>fd2a188c-bc9b-4702-9c47-b546b2614817</td>
            <td>com.kmong.iOS</td>
            <td>F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>home</td>
            <td>home</td>
            <td>view</td>
            <td>홈</td>
            <td>홈 (탭)</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
        </tr>
        <tr>
            <th>1</th>
            <td>e62dccef-dd70-4415-8a33-c8324ddaed38</td>
            <td>com.kmong.kmong</td>
            <td>8a871e50-0717-4aed-9bad-04ac3c3793be</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Samsung</td>
            <td>SM-N935S</td>
            <td>Android</td>
            <td>7.0</td>
            <td>3.3.5</td>
            <td>goal</td>
            <td>gig</td>
            <td>gig_detail</td>
            <td>view</td>
            <td>상품</td>
            <td>상품상세</td>
            <td>자기소개서</td>
            <td>문서작성</td>
            <td>자기소개서·이력서</td>
            <td>자기소개서</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
        </tr>
        <tr>
            <th>2</th>
            <td>14eb3197-db83-493a-b7be-83582960c40b</td>
            <td>com.kmong.iOS</td>
            <td>A9E5778A-8F3D-4597-9718-74BF953A9F64</td>
            <td>2018-09-27 15:00:00</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>0</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>12.0</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>inbox</td>
            <td>inbox_detail</td>
            <td>view</td>
            <td>메시지</td>
            <td>메시지목록-상세</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>unattributed</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
        </tr>
        <tr>
            <th>3</th>
            <td>f9bb91af-248b-44dc-9f5c-1c00b37ea97b</td>
            <td>com.kmong.iOS</td>
            <td>168761CB-CB67-4592-867D-52780D651297</td>
            <td>2018-09-27 15:00:01</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>1</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>foreground</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
        </tr>
        <tr>
            <th>4</th>
            <td>236e9946-7801-4898-b609-06c8ab1139dc</td>
            <td>com.kmong.iOS</td>
            <td>ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D</td>
            <td>2018-09-27 15:00:02</td>
            <td>2018</td>
            <td>9</td>
            <td>27</td>
            <td>15</td>
            <td>0</td>
            <td>2</td>
            <td>Apple</td>
            <td>iPhone</td>
            <td>iOS</td>
            <td>11.4.1</td>
            <td>4.0.4</td>
            <td>goal</td>
            <td>buyer</td>
            <td>buyer_order_track</td>
            <td>view</td>
            <td>거래관리</td>
            <td>메뉴목록-구매관리-거래메시지</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>web</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>NaN</td>
            <td>False</td>
            <td>False</td>
        </tr>
    </tbody>
</table>

In [72]:
# Write your code here!
df_ex.columns

Index(['row_uuid', 'app_package_name', 'user_id', 'event_datetime',
       'event_datetime_year', 'event_datetime_month', 'event_datetime_day',
       'event_datetime_hour', 'event_datetime_minute', 'event_datetime_second',
       'device_manufacturer', 'device_type', 'os_type', 'os_version',
       'app_version', 'event_category', 'view_category', 'view_id',
       'view_action', 'in_app_event_category', 'in_app_event_label',
       'source_type', 'channel', 'params_campaign', 'params_medium',
       'params_term', 'is_first_activity', 'is_first_goal_activity', 'lv1',
       'lv2', 'view_desc', 'funnel_name', 'funnel_desc', 'depth',
       'category_id', 'category_name', 'category1_id', 'category2_id',
       'categoryt3_id', 'category1', 'category2', 'category3'],
      dtype='object')

In [73]:
df_ex=df_ex.drop(columns=["in_app_event_category","in_app_event_label", "source_type",
"lv1", "lv2", "funnel_name", "depth", "category_id", "category1_id", "category2_id", "categoryt3_id"])

In [74]:
df_ex.columns

Index(['row_uuid', 'app_package_name', 'user_id', 'event_datetime',
       'event_datetime_year', 'event_datetime_month', 'event_datetime_day',
       'event_datetime_hour', 'event_datetime_minute', 'event_datetime_second',
       'device_manufacturer', 'device_type', 'os_type', 'os_version',
       'app_version', 'event_category', 'view_category', 'view_id',
       'view_action', 'channel', 'params_campaign', 'params_medium',
       'params_term', 'is_first_activity', 'is_first_goal_activity',
       'view_desc', 'funnel_desc', 'category_name', 'category1', 'category2',
       'category3'],
      dtype='object')

In [75]:
new_columns = ['row_uuid', 'app_package_name', 'user_id', 'event_datetime',
       'event_datetime_year', 'event_datetime_month', 'event_datetime_day',
       'event_datetime_hour', 'event_datetime_minute', 'event_datetime_second',
       'device_manufacturer', 'device_type', 'os_type', 'os_version',
       'app_version', 'event_category', 'view_category', 'view_id',
       'view_action', 'funnel_desc','view_desc','category_name', 'category1', 'category2',
       'category3','channel', 'params_campaign', 'params_medium',
       'params_term','is_first_activity', 'is_first_goal_activity',
        ]

In [76]:
df_ex=df_ex.reindex_axis(new_columns, axis=1)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
  """Entry point for launching an IPython kernel.

In [77]:
df_ex.head()

,row_uuid,app_package_name,user_id,event_datetime,event_datetime_year,event_datetime_month,event_datetime_day,event_datetime_hour,event_datetime_minute,event_datetime_second,device_manufacturer,device_type,os_type,os_version,app_version,event_category,view_category,view_id,view_action,funnel_desc,view_desc,category_name,category1,category2,category3,channel,params_campaign,params_medium,params_term,is_first_activity,is_first_goal_activity
0,fd2a188c-bc9b-4702-9c47-b546b2614817,com.kmong.iOS,F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,11.4.1,4.0.4,goal,home,home,view,홈,홈 (탭),NaN,NaN,NaN,NaN,unattributed,NaN,NaN,NaN,False,False
1,e62dccef-dd70-4415-8a33-c8324ddaed38,com.kmong.kmong,8a871e50-0717-4aed-9bad-04ac3c3793be,2018-09-28 00:00:00,2018,9,28,0,0,0,Samsung,SM-N935S,Android,7.0,3.3.5,goal,gig,gig_detail,view,상품,상품상세,자기소개서,문서작성,자기소개서·이력서,자기소개서,unattributed,NaN,NaN,NaN,False,False
2,14eb3197-db83-493a-b7be-83582960c40b,com.kmong.iOS,A9E5778A-8F3D-4597-9718-74BF953A9F64,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,12.0,4.0.4,goal,inbox,inbox_detail,view,메시지,메시지목록-상세,NaN,NaN,NaN,NaN,unattributed,NaN,NaN,NaN,False,False
3,f9bb91af-248b-44dc-9f5c-1c00b37ea97b,com.kmong.iOS,168761CB-CB67-4592-867D-52780D651297,2018-09-28 00:00:01,2018,9,28,0,0,1,Apple,iPhone,iOS,11.4.1,4.0.4,foreground,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,236e9946-7801-4898-b609-06c8ab1139dc,com.kmong.iOS,ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D,2018-09-28 00:00:02,2018,9,28,0,0,2,Apple,iPhone,iOS,11.4.1,4.0.4,goal,buyer,buyer_order_track,view,거래관리,메뉴목록-구매관리-거래메시지,NaN,NaN,NaN,NaN,web,NaN,NaN,NaN,False,False

**15. ```row_uuid```를 인덱스(index)로 지정해주세요.**

데이터를 다 정리했으면 마지막으로 인덱스(index)를 지정하고 마무리하겠습니다. 현재 가지고 있는 데이터에서 인덱스가 될 수 있을만한 컬럼은 ```row_uuid``` 입니다. 이 컬럼을 인덱스로 지정하면, 앞으로 데이터의 행(row)을 가져오고 분석할 때 큰 도움이 될 것 같습니다. 최종적으로는 다음의 결과가 나와야 합니다.

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>app_package_name</th>
      <th>user_id</th>
      <th>event_datetime</th>
      <th>event_datetime_year</th>
      <th>event_datetime_month</th>
      <th>event_datetime_day</th>
      <th>event_datetime_hour</th>
      <th>event_datetime_minute</th>
      <th>event_datetime_second</th>
      <th>device_manufacturer</th>
      <th>device_type</th>
      <th>os_type</th>
      <th>os_version</th>
      <th>app_version</th>
      <th>event_category</th>
      <th>view_category</th>
      <th>view_id</th>
      <th>view_action</th>
      <th>funnel_desc</th>
      <th>view_desc</th>
      <th>category_name</th>
      <th>category1</th>
      <th>category2</th>
      <th>category3</th>
      <th>channel</th>
      <th>params_campaign</th>
      <th>params_medium</th>
      <th>params_term</th>
      <th>is_first_activity</th>
      <th>is_first_goal_activity</th>
    </tr>
    <tr>
      <th>row_uuid</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>fd2a188c-bc9b-4702-9c47-b546b2614817</th>
      <td>com.kmong.iOS</td>
      <td>F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957</td>
      <td>2018-09-27 15:00:00</td>
      <td>2018</td>
      <td>9</td>
      <td>27</td>
      <td>15</td>
      <td>0</td>
      <td>0</td>
      <td>Apple</td>
      <td>iPhone</td>
      <td>iOS</td>
      <td>11.4.1</td>
      <td>4.0.4</td>
      <td>goal</td>
      <td>home</td>
      <td>home</td>
      <td>view</td>
      <td>홈</td>
      <td>홈 (탭)</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>unattributed</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>e62dccef-dd70-4415-8a33-c8324ddaed38</th>
      <td>com.kmong.kmong</td>
      <td>8a871e50-0717-4aed-9bad-04ac3c3793be</td>
      <td>2018-09-27 15:00:00</td>
      <td>2018</td>
      <td>9</td>
      <td>27</td>
      <td>15</td>
      <td>0</td>
      <td>0</td>
      <td>Samsung</td>
      <td>SM-N935S</td>
      <td>Android</td>
      <td>7.0</td>
      <td>3.3.5</td>
      <td>goal</td>
      <td>gig</td>
      <td>gig_detail</td>
      <td>view</td>
      <td>상품</td>
      <td>상품상세</td>
      <td>자기소개서</td>
      <td>문서작성</td>
      <td>자기소개서·이력서</td>
      <td>자기소개서</td>
      <td>unattributed</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>14eb3197-db83-493a-b7be-83582960c40b</th>
      <td>com.kmong.iOS</td>
      <td>A9E5778A-8F3D-4597-9718-74BF953A9F64</td>
      <td>2018-09-27 15:00:00</td>
      <td>2018</td>
      <td>9</td>
      <td>27</td>
      <td>15</td>
      <td>0</td>
      <td>0</td>
      <td>Apple</td>
      <td>iPhone</td>
      <td>iOS</td>
      <td>12.0</td>
      <td>4.0.4</td>
      <td>goal</td>
      <td>inbox</td>
      <td>inbox_detail</td>
      <td>view</td>
      <td>메시지</td>
      <td>메시지목록-상세</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>unattributed</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>f9bb91af-248b-44dc-9f5c-1c00b37ea97b</th>
      <td>com.kmong.iOS</td>
      <td>168761CB-CB67-4592-867D-52780D651297</td>
      <td>2018-09-27 15:00:01</td>
      <td>2018</td>
      <td>9</td>
      <td>27</td>
      <td>15</td>
      <td>0</td>
      <td>1</td>
      <td>Apple</td>
      <td>iPhone</td>
      <td>iOS</td>
      <td>11.4.1</td>
      <td>4.0.4</td>
      <td>foreground</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>236e9946-7801-4898-b609-06c8ab1139dc</th>
      <td>com.kmong.iOS</td>
      <td>ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D</td>
      <td>2018-09-27 15:00:02</td>
      <td>2018</td>
      <td>9</td>
      <td>27</td>
      <td>15</td>
      <td>0</td>
      <td>2</td>
      <td>Apple</td>
      <td>iPhone</td>
      <td>iOS</td>
      <td>11.4.1</td>
      <td>4.0.4</td>
      <td>goal</td>
      <td>buyer</td>
      <td>buyer_order_track</td>
      <td>view</td>
      <td>거래관리</td>
      <td>메뉴목록-구매관리-거래메시지</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>web</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
    </tr>
  </tbody>
</table>

In [78]:
# Write your code here!
df=df_ex.set_index('row_uuid')

In [79]:
df.head()

,app_package_name,user_id,event_datetime,event_datetime_year,event_datetime_month,event_datetime_day,event_datetime_hour,event_datetime_minute,event_datetime_second,device_manufacturer,device_type,os_type,os_version,app_version,event_category,view_category,view_id,view_action,funnel_desc,view_desc,category_name,category1,category2,category3,channel,params_campaign,params_medium,params_term,is_first_activity,is_first_goal_activity
row_uuid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
fd2a188c-bc9b-4702-9c47-b546b2614817,com.kmong.iOS,F36FAA62-ADAC-4AA5-9B00-1FD6CB7EE957,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,11.4.1,4.0.4,goal,home,home,view,홈,홈 (탭),NaN,NaN,NaN,NaN,unattributed,NaN,NaN,NaN,False,False
e62dccef-dd70-4415-8a33-c8324ddaed38,com.kmong.kmong,8a871e50-0717-4aed-9bad-04ac3c3793be,2018-09-28 00:00:00,2018,9,28,0,0,0,Samsung,SM-N935S,Android,7.0,3.3.5,goal,gig,gig_detail,view,상품,상품상세,자기소개서,문서작성,자기소개서·이력서,자기소개서,unattributed,NaN,NaN,NaN,False,False
14eb3197-db83-493a-b7be-83582960c40b,com.kmong.iOS,A9E5778A-8F3D-4597-9718-74BF953A9F64,2018-09-28 00:00:00,2018,9,28,0,0,0,Apple,iPhone,iOS,12.0,4.0.4,goal,inbox,inbox_detail,view,메시지,메시지목록-상세,NaN,NaN,NaN,NaN,unattributed,NaN,NaN,NaN,False,False
f9bb91af-248b-44dc-9f5c-1c00b37ea97b,com.kmong.iOS,168761CB-CB67-4592-867D-52780D651297,2018-09-28 00:00:01,2018,9,28,0,0,1,Apple,iPhone,iOS,11.4.1,4.0.4,foreground,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236e9946-7801-4898-b609-06c8ab1139dc,com.kmong.iOS,ACABB7C0-4C76-413A-B314-E5D6DA0D0E5D,2018-09-28 00:00:02,2018,9,28,0,0,2,Apple,iPhone,iOS,11.4.1,4.0.4,goal,buyer,buyer_order_track,view,거래관리,메뉴목록-구매관리-거래메시지,NaN,NaN,NaN,NaN,web,NaN,NaN,NaN,False,False

## 제출

과제를 다 끝내셨으면, datascience@dsschool.co.kr 로 제출해주시면 솔루션과 검토 결과를 드립니다. 과제를 제출하지 않으시더라도 솔루션은 다음 수업 시간에 제공해드립니다. 메일의 제목은 `[분석반 크몽 과제 제출] 홍길동 (슬랙 아이디 Gil-Dong Hong)`과 같이 해주시면 감사하겠습니다. (성함과 슬랙 아이디를 동시에 적어주셔야 저희가 성함과 아이디를 매칭할 수 있습니다)

수업이나 과제 관련 질문, 수료증 문의 등은 담당 튜터(조교)에게 문의 주세요. 영수증 발급 등의 문의는 support@dsschool.co.kr 로 메일 주시면 담당자분이 응대해주실 겁니다. 기타 궁금한 사항은 슬랙으로 문의 주세요!